trigger:
- main

pool:
  name: WorkerPool
  demands: Agent.OSArchitecture -equals ARM64

steps:
- task: qetza.replacetokens.replacetokens-task.replacetokens@3
  displayName: 'Replace tokens in **/*.json'
  inputs:
    targetFiles: '**/*.json'
    escapeType: json
    actionOnMissing: fail

- task: DockerCompose@0
  displayName: 'Build services BootstrapToAzure'
  inputs:
    containerregistrytype: 'Container Registry'
    additionalDockerComposeFiles: 'docker-compose.ci.yml'
    dockerComposeFileArgs: 'DOCKER_BUILD_SOURCE='
    action: 'Build services'
    additionalImageTags: '$(Build.BuildId)'
    includeLatestTag: true
    arguments: '--no-cache'

- task: Docker@2
  displayName: 'Stop BootstrapToAzure'
  inputs:
    command: stop
    container: BootstrapToAzure
  continueOnError: true

- bash: |
   echo 'Removing BootstrapToAzure'
   
   echo 'docker rm -f BootstrapToAzure'
   
   docker rm -f BootstrapToAzure
  displayName: 'Remove BootstrapToAzure'
  continueOnError: true

- bash: |
   echo 'Run BootstrapToAzure'
   
   echo 'docker run -d --restart=always --name BootstrapToAzure -v /var/run/docker.sock:/var/run/docker.sock -v /var/lib/docker/volumes/veriumminer_root_home/_data/:/root/veriumminer/ -v /var/lib/docker/volumes/verium_root_home/_data/:/root/verium/ -v /var/lib/docker/volumes/vericoin_root_home/_data/:/root/vericoin/ bootstraptoazureworkerservice'
   
   docker run -d --restart=always --name BootstrapToAzure -v /var/run/docker.sock:/var/run/docker.sock -v /var/lib/docker/volumes/veriumminer_root_home/_data/:/root/veriumminer/ -v /var/lib/docker/volumes/verium_root_home/_data/:/root/verium/ -v /var/lib/docker/volumes/vericoin_root_home/_data/:/root/vericoin/ bootstraptoazureworkerservice
  displayName: 'Run BootstrapToAzure'
